name = "QuanticsTCI"
uuid = "b11687fd-3a1c-4c41-97d0-998ab401d50e"
authors = ["Ritter.Marc <Ritter.Marc@physik.uni-muenchen.de> and contributors"]
version = "0.1.0"

[deps]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
